export const CURRICULUM_DATA = {
    "Intro to Python": {
        "prereqs": [],
        "description": "Beginner-friendly introduction to programming and problem-solving using Python.",
        "weeks": [
            { "week": 1, "topic": "Getting Started with Python", "description": "Install Python, choose an editor, run your first scripts, and understand what programming is.", "resources": [{ "title": "Python Full Course for Beginners", "url": "https://www.youtube.com/watch?v=K5KVEU3aaeQ", "type": "Video" }, { "title": "Python Beginner's Handbook (freeCodeCamp article hub)", "url": "https://www.freecodecamp.org/news/learn-python-free-python-courses-for-beginners/", "type": "Article" }], "deliverable": "Install Python and VS Code (or another IDE) and write a script that prints a custom welcome message with your name and grade." },
            { "week": 2, "topic": "Variables, Data Types, and Input/Output", "description": "Use variables, basic data types, and user input/output to build simple interactive programs.", "resources": [{ "title": "Python Full Course for Beginners | Sections on variables & input", "url": "https://www.youtube.com/watch?v=H2EJuAcrZYU", "type": "Video" }, { "title": "Python 3 Official Tutorial – An Informal Introduction to Python", "url": "https://docs.python.org/3/tutorial/introduction.html", "type": "Article" }], "deliverable": "Write a script that asks the user for their name and three favorite numbers, stores them in variables, and prints a formatted summary." },
            { "week": 3, "topic": "Conditionals and Boolean Logic", "description": "Use if/elif/else and boolean expressions to control program flow.", "resources": [{ "title": "Python Full Course for Beginers – If Statements & Logic", "url": "https://www.youtube.com/watch?v=rfscVS0vtbw", "type": "Video" }, { "title": "Python 3 Tutorial – More Control Flow Tools", "url": "https://docs.python.org/3/tutorial/controlflow.html", "type": "Article" }], "deliverable": "Create a simple grade calculator that takes a numeric score and prints a letter grade using if/elif/else." },
            { "week": 4, "topic": "Loops and Basic Algorithms", "description": "Use for and while loops to repeat actions and implement simple algorithms.", "resources": [{ "title": "Learn Python - Loops Section (freeCodeCamp course)", "url": "https://www.youtube.com/watch?v=rfscVS0vtbw", "type": "Video" }, { "title": "Python 3 Tutorial – For Statements", "url": "https://docs.python.org/3/tutorial/controlflow.html#for-statements", "type": "Article" }], "deliverable": "Write a number guessing game that picks a random number and lets the user guess until they are correct, giving hints each time." },
            { "week": 5, "topic": "Functions and Code Organization", "description": "Create and use functions to organize and reuse code.", "resources": [{ "title": "Intermediate Python Programming Course – Functions", "url": "https://www.youtube.com/watch?v=HGOBQPFzWKo", "type": "Video" }, { "title": "Python 3 Tutorial – Defining Functions", "url": "https://docs.python.org/3/tutorial/controlflow.html#defining-functions", "type": "Article" }], "deliverable": "Refactor your number guessing game into multiple functions (e.g., get_guess, check_guess, run_game)." },
            { "week": 6, "topic": "Lists, Tuples, and Dictionaries", "description": "Use built-in data structures to store and manage collections of data.", "resources": [{ "title": "Ultimate Beginner's Python Course (data structures sections)", "url": "https://www.freecodecamp.org/news/ultimate-beginners-python-course/", "type": "Article" }, { "title": "Python 3 Tutorial – Data Structures", "url": "https://docs.python.org/3/tutorial/datastructures.html", "type": "Article" }], "deliverable": "Build a contacts manager that stores names, phone numbers, and emails in dictionaries inside a list and prints them in a readable format." },
            { "week": 7, "topic": "File I/O and Simple Persistence", "description": "Read from and write to text files so programs can save and load data.", "resources": [{ "title": "Python Tutorial – Reading and Writing Files", "url": "https://docs.python.org/3/tutorial/inputoutput.html#reading-and-writing-files", "type": "Article" }, { "title": "Python File Handling Crash Course", "url": "https://www.youtube.com/watch?v=Uh2ebFW8OYM", "type": "Video" }], "deliverable": "Extend your contacts manager to save the contact list to a file and load it again when the program starts." },
            { "week": 8, "topic": "Putting It Together – Mini Project", "description": "Combine input, conditionals, loops, functions, and data structures into a small cohesive project.", "resources": [{ "title": "Beginner Python Project Ideas", "url": "https://www.freecodecamp.org/news/python-projects-for-beginners/", "type": "Article" }], "deliverable": "Build a text-based application (e.g., a to‑do list, quiz game, or flashcard app) that uses loops, functions, and lists or dictionaries." },
            { "week": 9, "topic": "Final Assessment", "description": "Choose and complete one Ellis Activity (Builder, Academic, or Communicator) to demonstrate mastery of Intro to Python.", "resources": [], "deliverable": "Submit your chosen Ellis Activity (project, problem set, or tutorial) with code and reflection." }
        ],
        "ellis_activities": {
            "builder": { "title": "Personal Productivity App", "description": "Build a command-line productivity app (to‑do list, habit tracker, or study timer) that uses functions, lists/dictionaries, and file saving." },
            "academic": { "title": "Intro Python Problem Set", "description": "Complete a custom problem set of 12–15 exercises drawn from freeCodeCamp's Python practice and similar sources (loops, conditionals, functions, lists)." },
            "communicator": { "title": "Teach Python Basics", "description": "Create a 10–15 minute video, slide deck, or written tutorial explaining variables, conditionals, and loops in Python with at least three example programs." }
        }
    },
    "Intermediate Python": {
        "prereqs": ["Intro to Python"],
        "description": "Deepen Python skills with OOP, modules, error handling, and introductory libraries.",
        "weeks": [
            { "week": 1, "topic": "Review and Deeper Functions", "description": "Review core Python and explore parameters, return values, and scope in more depth.", "resources": [{ "title": "Intermediate Python Programming Course", "url": "https://www.youtube.com/watch?v=HGOBQPFzWKo", "type": "Video" }, { "title": "Python 3 Tutorial – More on Defining Functions", "url": "https://docs.python.org/3/tutorial/controlflow.html#more-on-defining-functions", "type": "Article" }], "deliverable": "Refactor a previous project to use well-designed functions with clear parameters and return values." },
            { "week": 2, "topic": "Modules, Packages, and Virtual Environments", "description": "Import modules, install packages, and manage environments.", "resources": [{ "title": "Python Modules and Packages – Tutorial", "url": "https://docs.python.org/3/tutorial/modules.html", "type": "Article" }, { "title": "How to Use pip and Virtual Environments", "url": "https://www.youtube.com/watch?v=UO98lJQ3QGI", "type": "Video" }], "deliverable": "Create a small project that uses at least one external package (e.g., requests) installed via pip." },
            { "week": 3, "topic": "Object-Oriented Programming (Classes and Objects)", "description": "Model real-world entities using classes, objects, attributes, and methods.", "resources": [{ "title": "Object-Oriented Programming in Python (freeCodeCamp)", "url": "https://www.youtube.com/watch?v=JeznW_7DlB0", "type": "Video" }, { "title": "Python 3 Tutorial – Classes", "url": "https://docs.python.org/3/tutorial/classes.html", "type": "Article" }], "deliverable": "Implement a class-based system (e.g., Student, Course, Enrollment) and demonstrate creating and using multiple objects." },
            { "week": 4, "topic": "Error Handling and Exceptions", "description": "Write robust code with try/except blocks and custom exceptions.", "resources": [{ "title": "Python Exceptions and Error Handling", "url": "https://docs.python.org/3/tutorial/errors.html", "type": "Article" }, { "title": "Exception Handling in Python Crash Course", "url": "https://www.youtube.com/watch?v=NIWwJbo-9_8", "type": "Video" }], "deliverable": "Update a previous project to gracefully handle invalid input and file errors using exceptions." },
            { "week": 5, "topic": "Working with JSON and APIs", "description": "Use JSON data and call simple web APIs using Python.", "resources": [{ "title": "Python Requests and JSON – Working with APIs", "url": "https://www.youtube.com/watch?v=tb8gHvYlCFs", "type": "Video" }, { "title": "Python json Module", "url": "https://docs.python.org/3/library/json.html", "type": "Article" }], "deliverable": "Build a script that calls a public API (such as a joke, quotes, or weather API) and prints formatted output." },
            { "week": 6, "topic": "Comprehensions and Iterators", "description": "Use list/dict comprehensions and understand iterators and generators.", "resources": [{ "title": "Python List Comprehensions Tutorial", "url": "https://www.youtube.com/watch?v=AhSvKGTh28Q", "type": "Video" }, { "title": "List Comprehensions in Python (Real Python free article)", "url": "https://realpython.com/list-comprehension-python/", "type": "Article" }], "deliverable": "Refactor loops in one of your scripts to use comprehensions where appropriate and compare readability." },
            { "week": 7, "topic": "Intro to Testing and Debugging", "description": "Learn basic debugging techniques and write simple unit tests.", "resources": [{ "title": "Debugging in Python – Beginner Tutorial", "url": "https://www.youtube.com/watch?v=8q_en3DIzOQ", "type": "Video" }, { "title": "Python unittest Module", "url": "https://docs.python.org/3/library/unittest.html", "type": "Article" }], "deliverable": "Write at least five unit tests for an existing project using unittest and fix any bugs discovered." },
            { "week": 8, "topic": "Intermediate Project", "description": "Plan and implement a medium-size project using OOP, external libraries, and tests.", "resources": [{ "title": "Intermediate Python Project Ideas", "url": "https://www.freecodecamp.org/news/python-projects-junior-developers/", "type": "Article" }], "deliverable": "Start an intermediate project (e.g., API‑powered dashboard, CLI notes app, or mini game) and implement core features." },
            { "week": 9, "topic": "Final Assessment", "description": "Complete one Ellis Activity (Builder, Academic, or Communicator) to demonstrate intermediate Python skills.", "resources": [], "deliverable": "Submit final project or alternative Ellis Activity with code, tests, and a short write-up." }
        ],
        "ellis_activities": {
            "builder": { "title": "API-Powered Dashboard", "description": "Build a command-line or simple GUI dashboard that pulls live data from at least two public APIs and presents it cleanly." },
            "academic": { "title": "Intermediate Python Problem Set", "description": "Complete a curated set of 15–20 problems involving OOP, file handling, and list/dict comprehensions (drawn from free problem sources like CodingBat or freeCodeCamp practice)." },
            "communicator": { "title": "Explain OOP in Python", "description": "Create a detailed tutorial, slide deck, or video that teaches classes, objects, and exceptions in Python, including at least two live-coded demos." }
        }
    }
};
